# 管理员对应的 Telegram 用户 ID
# 你可以通过 /info 命令获取你的用户 ID
admin: 123456789
# 开发者对应的 Telegram 用户 ID
# 如果你希望 fork 这个项目并进行开发，你可以在这里更改成你的用户 ID，用户不推荐更改这部分
# 这部分仅限于汇报链接跟踪参数去除的问题
dev: 616760897

start_telegram_bot: true
also_start_matrix_bot: false

matrix:
  homeserver: "https://matrix.org"
  user_id: "@your_bot:matrix.org"
  # Token 请使用登录后生成的 Access Token，一般可以在客户端的设置页面找到，然后设置到 MATRIX_BOT_TOKEN 环境变量中
  # 如果你想使用一个新的 token，可以使用 helpers/matrix_login.py 脚本生成一个新的 token


# global features settings
features:
  # 启用 /打 这样的指令
  actions:
    enable: true
  # 启用 1/0 翻转
  bitflip:
    enable: true
  # 启用转发到联邦宇宙
  fedi:
    enable: true
  # 启用链接解析/清理
  link:
    enable: true
  # 启用互送头衔
  promote:
    enable: true
  # 启用复读
  repeater:
    enable: true
  # 启用统计
  stats:
    enable: true
  # 启用解除频道消息在群组的置顶
  unpin:
    enable: true
    regex: ''
  # 启用欢迎新成员
  welcome:
    enable: false
    message: "嘤嘤嘤"
  # 启用反频道马甲
  anti_anonymous:
    enable: false
    also_ban: false
    whitelist:
      - 123456789  # 默认允许的频道身份 ID 列表

# group features settings
# 群组 id，使用 bot api（bot 内置的 info 命令）
-1002000000000:
  # 要启用的功能
  actions:
    enable: true
  unpin:
    enable: false
    regex: "r'#pin'"
